In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'Sample.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2019-103800,03-01-2019,07-01-2019,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2019-112326,04-01-2019,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2019-112326,04-01-2019,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2019-112326,04-01-2019,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2019-141817,05-01-2019,12-01-2019,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2022-143259,30-12-2022,03-01-2023,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2022-115427,30-12-2022,03-01-2023,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2022-156720,30-12-2022,03-01-2023,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2022-143259,30-12-2022,03-01-2023,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2022-143500,30-12-2022,03-01-2023,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [5]:
# 1. Write a function that returns all orders where Sales > 500.

def high_sales_orders(df):
    return df[df['Sales'] > 500]
    
print(high_sales_orders(df))

       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
5           6  US-2019-167199  06-01-2019  10-01-2019  Standard Class
8           9  US-2019-167199  06-01-2019  10-01-2019  Standard Class
12         13  US-2019-167199  06-01-2019  10-01-2019  Standard Class
22         23  US-2019-109232  13-01-2019  16-01-2019    Second Class
29         30  US-2019-162775  13-01-2019  15-01-2019    Second Class
...       ...             ...         ...         ...             ...
10121   10122  US-2022-145219  24-12-2022  25-12-2022     First Class
10137   10138  US-2022-114055  25-12-2022  29-12-2022    Second Class
10149   10150  US-2022-121741  26-12-2022  26-12-2022        Same Day
10169   10170  US-2022-163979  28-12-2022  02-01-2023    Second Class
10172   10173  US-2022-158526  29-12-2022  01-01-2023    Second Class

      Customer ID      Customer Name      Segment Country/Region  \
5        ME-17320      Maria Etezadi  Home Office  United States
8        ME-17320      Maria Etezadi  Home Office  United States
12       ME-17320      Maria Etezadi  Home Office  United States
22       ND-18370  Natalie DeCherney     Consumer  United States
29       CS-12250    Chris Selesnick    Corporate  United States
...           ...                ...          ...            ...
10121    RM-19675      Robert Marley  Home Office  United States
10137    MH-18115     Mick Hernandez  Home Office  United States
10149    YC-21895     Yoseph Carroll    Corporate  United States
10169    KH-16690   Kristen Hastings    Corporate  United States
10172    KH-16360   Katherine Hughes     Consumer  United States

                 City  ... Postal Code   Region       Product ID  \
5           Henderson  ...       42420    South  FUR-CH-10004063
8           Henderson  ...       42420    South  OFF-BI-10004632
12          Henderson  ...       42420    South  TEC-PH-10004539
22     Mount Pleasant  ...       29464    South  FUR-CH-10000422
29       Bossier City  ...       71111    South  OFF-ST-10000025
...               ...  ...         ...      ...              ...
10121     Los Angeles  ...       90049     West  TEC-CO-10001449
10137      Huntsville  ...       35810    South  OFF-PA-10000994
10149         Fremont  ...       68025  Central  OFF-ST-10004459
10169   San Francisco  ...       94110     West  OFF-ST-10003208
10172      Louisville  ...       40214    South  FUR-CH-10002602

              Category Sub-Category  \
5            Furniture       Chairs
8      Office Supplies      Binders
12          Technology       Phones
22           Furniture       Chairs
29     Office Supplies      Storage
...                ...          ...
10121       Technology      Copiers
10137  Office Supplies        Paper
10149  Office Supplies      Storage
10169  Office Supplies      Storage
10172        Furniture       Chairs

                                            Product Name     Sales  Quantity  \
5                Global Deluxe High-Back Manager's Chair  2573.820         9
8                    Ibico Hi-Tech Manual Binding System   609.980         2
12     Wireless Extenders zBoost YX545 SOHO Signal Bo...   755.960         4
22            Global Highback Leather Tilter in Burgundy   545.940         6
29       Fellowes Stor/Drawer Steel Plus Storage Drawers   572.580         6
...                                                  ...       ...       ...
10121               Hewlett Packard LaserJet 3310 Copier  2879.952         6
10137                                         Xerox 1915   629.100         6
10149                        Tennsco Single-Tier Lockers   750.680         2
10169                 Adjustable Depth Letter/Legal Cart   725.840         4
10172  DMI Arturo Collection Mission-style Design Woo...  1207.840         8

       Discount     Profit
5           0.0   746.4078
8           0.0   274.4910
12          0.0   204.1092
22          0.0    87.3504
29          0.0    34.3548
...         ...        ...
10121       0.2  1007.9832
10137       0.0   301.9680
10149       0.0    37.5340
10169       0.0   210.4936
10172       0.0   314.0384

[1175 rows x 21 columns]

In [4]:
# 2. Create a function to return orders where Category = 'Technology' and Profit > 100.

def tech_profit_orders(df):
    return df[(df['Category'] == 'Technology') & (df['Profit'] > 100)]
# result = tech_profit_orders(df)

print(tech_profit_orders(df))

       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
12         13  US-2019-167199  06-01-2019  10-01-2019  Standard Class
13         14  US-2019-167199  06-01-2019  10-01-2019  Standard Class
31         32  US-2019-162775  13-01-2019  15-01-2019    Second Class
59         60  US-2019-147627  20-01-2019  26-01-2019  Standard Class
84         85  US-2019-140795  01-02-2019  03-02-2019     First Class
...       ...             ...         ...         ...             ...
9983     9984  US-2022-151799  14-12-2022  18-12-2022  Standard Class
10086   10087  US-2022-149699  22-12-2022  24-12-2022     First Class
10106   10107  US-2022-162670  23-12-2022  28-12-2022    Second Class
10121   10122  US-2022-145219  24-12-2022  25-12-2022     First Class
10122   10123  US-2022-124296  24-12-2022  28-12-2022  Standard Class

      Customer ID         Customer Name      Segment Country/Region  \
12       ME-17320         Maria Etezadi  Home Office  United States
13       ME-17320         Maria Etezadi  Home Office  United States
31       CS-12250       Chris Selesnick    Corporate  United States
59       HL-15040          Hunter Lopez     Consumer  United States
84       BD-11500       Bradley Drucker     Consumer  United States
...           ...                   ...          ...            ...
9983     BF-11170            Ben Ferrer  Home Office  United States
10086    CM-12115          Chad McGuire     Consumer  United States
10106    MF-18250        Monica Federle    Corporate  United States
10121    RM-19675         Robert Marley  Home Office  United States
10122    CS-12355  Christine Sundaresam     Consumer  United States

               City  ... Postal Code   Region       Product ID    Category  \
12        Henderson  ...       42420    South  TEC-PH-10004539  Technology
13        Henderson  ...       42420    South  TEC-PH-10004977  Technology
31     Bossier City  ...       71111    South  TEC-AC-10003174  Technology
59        Jonesboro  ...       72401    South  TEC-PH-10001061  Technology
84        Green Bay  ...       54302  Central  TEC-AC-10001432  Technology
...             ...  ...         ...      ...              ...         ...
9983       Lawrence  ...       01841     East  TEC-CO-10002313  Technology
10086   Los Angeles  ...       90008     West  TEC-AC-10000474  Technology
10106   Little Rock  ...       72209    South  TEC-PH-10003601  Technology
10121   Los Angeles  ...       90049     West  TEC-CO-10001449  Technology
10122     Lafayette  ...       70506    South  TEC-MA-10003183  Technology

      Sub-Category                                       Product Name  \
12          Phones  Wireless Extenders zBoost YX545 SOHO Signal Bo...
13          Phones                                        GE 30524EE4
31     Accessories    Plantronics S12 Corded Telephone Headset System
59          Phones                                    Apple iPhone 5C
84     Accessories                       Enermax Aurora Lite Keyboard
...            ...                                                ...
9983       Copiers                      Canon PC1080F Personal Copier
10086  Accessories  Kensington Expert Mouse Optical USB Trackball ...
10106       Phones  Ativa D5772 2-Line 5.8GHz Digital Expandable C...
10121      Copiers               Hewlett Packard LaserJet 3310 Copier
10122     Machines    DYMO CardScan Personal V9 Business Card Scanner

          Sales  Quantity  Discount     Profit
12      755.960         4       0.0   204.1092
13      391.980         2       0.0   113.6742
31      646.740         6       0.0   258.6960
59      699.930         7       0.0   181.9818
84      468.900         6       0.0   206.3160
...         ...       ...       ...        ...
9983   1199.980         2       0.0   467.9922
10086   474.950         5       0.0   142.4850
10106   494.970         3       0.0   148.4910
10121  2879.952         6       0.2  1007.9832
10122   479.970         3       0.0   239.9850

[357 rows x 21 columns]

In [8]:
# 3. Write a function to create a new column 'Profit_Status' where Profit > 0 → 'Profit' else 'Loss'.

def add_profit_status(df):
    df['Profit_Status'] = 'Loss'
    df.loc[df['Profit'] > 0, 'Profit_Status'] = 'Profit'
    return df

print(add_profit_status(df))

       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0           1  US-2019-103800  03-01-2019  07-01-2019  Standard Class
1           2  US-2019-112326  04-01-2019  08-01-2019  Standard Class
2           3  US-2019-112326  04-01-2019  08-01-2019  Standard Class
3           4  US-2019-112326  04-01-2019  08-01-2019  Standard Class
4           5  US-2019-141817  05-01-2019  12-01-2019  Standard Class
...       ...             ...         ...         ...             ...
10189   10190  US-2022-143259  30-12-2022  03-01-2023  Standard Class
10190   10191  US-2022-115427  30-12-2022  03-01-2023  Standard Class
10191   10192  US-2022-156720  30-12-2022  03-01-2023  Standard Class
10192   10193  US-2022-143259  30-12-2022  03-01-2023  Standard Class
10193   10194  CA-2022-143500  30-12-2022  03-01-2023  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ...   Region       Product ID         Category  \
0            Houston  ...  Central  OFF-PA-10000174  Office Supplies
1         Naperville  ...  Central  OFF-BI-10004094  Office Supplies
2         Naperville  ...  Central  OFF-LA-10003223  Office Supplies
3         Naperville  ...  Central  OFF-ST-10002743  Office Supplies
4       Philadelphia  ...     East  OFF-AR-10003478  Office Supplies
...              ...  ...      ...              ...              ...
10189  New York City  ...     East  OFF-BI-10003684  Office Supplies
10190      Fairfield  ...     West  OFF-BI-10004632  Office Supplies
10191       Loveland  ...     West  OFF-FA-10003472  Office Supplies
10192  New York City  ...     East  TEC-PH-10004774       Technology
10193  Charlottetown  ...     East  OFF-BI-10004040  Office Supplies

      Sub-Category                                       Product Name  \
0            Paper  Message Book, Wirebound, Four 5 1/2" X 4" Form...
1          Binders         GBC Standard Plastic Binding Systems Combs
2           Labels                                          Avery 508
3          Storage                      SAFCO Boltless Steel Shelving
4              Art  Avery Hi-Liter EverBold Pen Style Fluorescent ...
...            ...                                                ...
10189      Binders               Wilson Jones Legal Size Ring Binders
10190      Binders                                 GBC Binding covers
10191    Fasteners                                Bagged Rubber Bands
10192       Phones                          Gear Head AU3700S Headset
10193      Binders                        Wilson Jones Impact Binders

         Sales Quantity  Discount   Profit  Profit_Status
0       16.448        2       0.2   5.5512         Profit
1        3.540        2       0.8  -5.4870           Loss
2       11.784        3       0.2   4.2717         Profit
3      272.736        3       0.2 -64.7748           Loss
4       19.536        3       0.2   4.8840         Profit
...        ...      ...       ...      ...            ...
10189   52.776        3       0.2  19.7910         Profit
10190   20.720        2       0.2   6.4750         Profit
10191    3.024        3       0.2  -0.6048           Loss
10192   90.930        7       0.0   2.7279         Profit
10193    3.024        3       0.2  -0.6048           Loss

[10194 rows x 22 columns]

In [9]:
# 4. Write a function to return total sales per region.

def total_sales_region(df):
    return df.groupby('Region')['Sales'].sum()

print(total_sales_region(df))

Region
Central    503170.6728
East       691828.1680
South      391721.9050
West       739813.6085
Name: Sales, dtype: float64

In [12]:
# 5. Write a function to return top 5 highest profit orders.

def top5_profit_orders(df):
    return df.sort_values(by='Profit', ascending=False).head(5)

print(top5_profit_orders(df))

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
5894    5895  US-2021-118689  02-10-2021  09-10-2021  Standard Class
7255    7256  US-2022-140151  23-03-2022  25-03-2022     First Class
9517    9518  US-2022-166709  17-11-2022  22-11-2022  Standard Class
6674    6675  US-2021-117121  17-12-2021  21-12-2021  Standard Class
1203    1204  US-2019-116904  23-09-2019  28-09-2019  Standard Class

     Customer ID  Customer Name    Segment Country/Region         City  ...  \
5894    TC-20980   Tamara Chand  Corporate  United States    Lafayette  ...
7255    RB-19360   Raymond Buch   Consumer  United States      Seattle  ...
9517    HL-15040   Hunter Lopez   Consumer  United States       Newark  ...
6674    AB-10105  Adrian Barton   Consumer  United States      Detroit  ...
1203    SC-20095   Sanjit Chand   Consumer  United States  Minneapolis  ...

       Region       Product ID         Category Sub-Category  \
5894  Central  TEC-CO-10004722       Technology      Copiers
7255     West  TEC-CO-10004722       Technology      Copiers
9517     East  TEC-CO-10004722       Technology      Copiers
6674  Central  OFF-BI-10000545  Office Supplies      Binders
1203  Central  OFF-BI-10001120  Office Supplies      Binders

                                          Product Name     Sales Quantity  \
5894             Canon imageCLASS 2200 Advanced Copier  17499.95        5
7255             Canon imageCLASS 2200 Advanced Copier  13999.96        4
9517             Canon imageCLASS 2200 Advanced Copier  10499.97        3
6674  GBC Ibimaster 500 Manual ProClick Binding System   9892.74       13
1203              Ibico EPK-21 Electric Binding System   9449.95        5

      Discount     Profit  Profit_Status
5894       0.0  8399.9760         Profit
7255       0.0  6719.9808         Profit
9517       0.0  5039.9856         Profit
6674       0.0  4946.3700         Profit
1203       0.0  4630.4755         Profit

[5 rows x 22 columns]

In [13]:
# 6. Write a function to fill missing values in 'Postal Code' with 0.

def fill_postal_code(df):
    df['Postal Code'] = df['Postal Code'].fillna(0)
    return df

print(fill_postal_code(df))

       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0           1  US-2019-103800  03-01-2019  07-01-2019  Standard Class
1           2  US-2019-112326  04-01-2019  08-01-2019  Standard Class
2           3  US-2019-112326  04-01-2019  08-01-2019  Standard Class
3           4  US-2019-112326  04-01-2019  08-01-2019  Standard Class
4           5  US-2019-141817  05-01-2019  12-01-2019  Standard Class
...       ...             ...         ...         ...             ...
10189   10190  US-2022-143259  30-12-2022  03-01-2023  Standard Class
10190   10191  US-2022-115427  30-12-2022  03-01-2023  Standard Class
10191   10192  US-2022-156720  30-12-2022  03-01-2023  Standard Class
10192   10193  US-2022-143259  30-12-2022  03-01-2023  Standard Class
10193   10194  CA-2022-143500  30-12-2022  03-01-2023  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ...   Region       Product ID         Category  \
0            Houston  ...  Central  OFF-PA-10000174  Office Supplies
1         Naperville  ...  Central  OFF-BI-10004094  Office Supplies
2         Naperville  ...  Central  OFF-LA-10003223  Office Supplies
3         Naperville  ...  Central  OFF-ST-10002743  Office Supplies
4       Philadelphia  ...     East  OFF-AR-10003478  Office Supplies
...              ...  ...      ...              ...              ...
10189  New York City  ...     East  OFF-BI-10003684  Office Supplies
10190      Fairfield  ...     West  OFF-BI-10004632  Office Supplies
10191       Loveland  ...     West  OFF-FA-10003472  Office Supplies
10192  New York City  ...     East  TEC-PH-10004774       Technology
10193  Charlottetown  ...     East  OFF-BI-10004040  Office Supplies

      Sub-Category                                       Product Name  \
0            Paper  Message Book, Wirebound, Four 5 1/2" X 4" Form...
1          Binders         GBC Standard Plastic Binding Systems Combs
2           Labels                                          Avery 508
3          Storage                      SAFCO Boltless Steel Shelving
4              Art  Avery Hi-Liter EverBold Pen Style Fluorescent ...
...            ...                                                ...
10189      Binders               Wilson Jones Legal Size Ring Binders
10190      Binders                                 GBC Binding covers
10191    Fasteners                                Bagged Rubber Bands
10192       Phones                          Gear Head AU3700S Headset
10193      Binders                        Wilson Jones Impact Binders

         Sales Quantity  Discount   Profit  Profit_Status
0       16.448        2       0.2   5.5512         Profit
1        3.540        2       0.8  -5.4870           Loss
2       11.784        3       0.2   4.2717         Profit
3      272.736        3       0.2 -64.7748           Loss
4       19.536        3       0.2   4.8840         Profit
...        ...      ...       ...      ...            ...
10189   52.776        3       0.2  19.7910         Profit
10190   20.720        2       0.2   6.4750         Profit
10191    3.024        3       0.2  -0.6048           Loss
10192   90.930        7       0.0   2.7279         Profit
10193    3.024        3       0.2  -0.6048           Loss

[10194 rows x 22 columns]

In [18]:
# 7. Write a function to apply discount rule: If Sales > 1000 → 20% discount else → 10%.

def apply_discount(df):
    df['Discount'] = 0.0
    df.loc[df['Sales'] > 1000, 'Discount'] = df['Sales'] * 0.20
    df.loc[df['Sales'] <= 1000, 'Discount'] = df['Sales'] * 0.10
    return df

df = apply_discount(df)

print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  US-2019-103800  03-01-2019  07-01-2019  Standard Class    DP-13000
1       2  US-2019-112326  04-01-2019  08-01-2019  Standard Class    PO-19195
2       3  US-2019-112326  04-01-2019  08-01-2019  Standard Class    PO-19195
3       4  US-2019-112326  04-01-2019  08-01-2019  Standard Class    PO-19195
4       5  US-2019-141817  05-01-2019  12-01-2019  Standard Class    MB-18085

   Customer Name      Segment Country/Region          City  ...   Region  \
0  Darren Powers     Consumer  United States       Houston  ...  Central
1  Phillina Ober  Home Office  United States    Naperville  ...  Central
2  Phillina Ober  Home Office  United States    Naperville  ...  Central
3  Phillina Ober  Home Office  United States    Naperville  ...  Central
4     Mick Brown     Consumer  United States  Philadelphia  ...     East

        Product ID         Category Sub-Category  \
0  OFF-PA-10000174  Office Supplies        Paper
1  OFF-BI-10004094  Office Supplies      Binders
2  OFF-LA-10003223  Office Supplies       Labels
3  OFF-ST-10002743  Office Supplies      Storage
4  OFF-AR-10003478  Office Supplies          Art

                                        Product Name    Sales Quantity  \
0  Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448        2
1         GBC Standard Plastic Binding Systems Combs    3.540        2
2                                          Avery 508   11.784        3
3                      SAFCO Boltless Steel Shelving  272.736        3
4  Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536        3

   Discount   Profit  Profit_Status
0    1.6448   5.5512         Profit
1    0.3540  -5.4870           Loss
2    1.1784   4.2717         Profit
3   27.2736 -64.7748           Loss
4    1.9536   4.8840         Profit

[5 rows x 22 columns]

In [24]:
# 8. Write a function to return all unique cities.

pd.DataFrame(df['City'].unique(), columns=['City'])

             City
0         Houston
1      Naperville
2    Philadelphia
3       Henderson
4          Athens
..            ...
537      Whittier
538       Abilene
539      Palatine
540   Port Orange
541       Danbury

[542 rows x 1 columns]

In [28]:
# 9. Write a function that returns total Sales and total Profit.

def total_sales_profit(df):
    return df['Sales'].sum(), df['Profit'].sum()

sales, profit = total_sales_profit(df)

print("Total Sales:", sales)
print("Total Profit:", profit)

Total Sales: 2326534.3543
Total Profit: 292296.81460000004

In [4]:
# 10. Write a function to return average sales per category only for 'West' region.

def avg_sales_west(df):
    return df[df['Region'] == 'West'].groupby('Category')['Sales'].mean()

print(avg_sales_west(df))

Category
Furniture          354.666299
Office Supplies    118.454679
Technology         416.420079
Name: Sales, dtype: float64